@startuml
left to right direction

actor user as U

rectangle "userStory" {
    usecase "arriver et visiter le site" as uc1
    usecase "lire la description du site et le principe"  as uc2
    usecase "accepter la geolocalisation"  as uc3
    usecase "rechercher un fermier dans une zone délimitée"  as uc4
    usecase "rechercher un fermier en fonction du produit"  as uc5
    usecase "regarder la description d'une ferme, ses images/produits et sa localisation"  as uc6
    usecase "contacter un admin"  as uc7
    usecase "lire les mentions légales"  as uc8
    usecase "modifier ses identifiants" as uc9
    usecase "modifier son mot de passe" as uc10
    usecase "supprimer son compte" as uc11
    usecase "modifier les parametres de son compte" as uc12
    usecase "ajouter des fermes en favoris" as uc13
}

U --> uc1
U --> uc2
U --> uc3
U --> uc4
U --> uc5
U --> uc6
U --> uc7
U --> uc8
U --> uc9
U --> uc10
U --> uc11
U --> uc12
U --> uc13

note right of uc1
    le user va pouvoir se rendre sur le site et visiter celui ci
end note
note right of uc2
    le user va prendre connaissance de l utiliter du site et sa démarche
end note
note right of uc3
    le user va pouvoir accepter la géolocalisation afin de faciliter la recherche autour de lui ou non
end note
note right of uc4
    le user va pouvoir effectuer la recherche d une ferme en y mettant une limite en km a partir d une ville ou d une adresse
end note
note right of uc5
    le user va pourvoir effectuer la recherche d une ferme en fonction du type de produit qu il recherche
end note
note right of uc6
    le user va pouvoir regarder la description d une ferme, voir ses images et les produits de celui ci
end note
note right of uc7
    le user va pouvoir contacter un admin via un formulaire de contact 
end note
note right of uc8
    le user va pouvoir prendre note des mentions légales du site
end note
note right of uc9
    le user va pouvoir modifier ses identifiants
end note
note right of uc10
    le user va pouvoir modifier son mot de passe
end note
note right of uc11
    le user va pouvoir supprimer son compte
end note
note right of uc12
    le user va pouvoir modifier ses parametres de compte tel que les notifications
end note
note right of uc13
    le user va pouvoir ajouter des fermes en favoris pour suivre l actualités de celle ci 
end note