@startuml diagramme sequence modification image

actor User as U
participant Application as App
participant Serveur as S
participant BaseDonnees as Bdd

U -> App :Clique pour valider la modif de l'image
App -> S :Demande de modification image
S -> Bdd :Verification de modification image

Bdd --> S :Validation de modification image
S --> App :Confirmation de modification image
App --> U :Redirection vers la page produit