@startuml diagramme de deploiement
left to right direction
title Diagramme de Déploiement

node "Client Mobile" as Cl {
    component ReactNativeApp as BR
}
node "Serveur Web" as SW {
    component PHP as PHP 
    artifact Symfony
    
}
database "Base de Données" as DB {
    component MySQL 
}
' node "Messagerie" {
'     component mailto as MSG
' }

Cl -- SW :https
PHP ..> Symfony :utilse
Symfony -> MySQL :ORM doctrine
SW -- DB: TCP 
' SW -- MSG :SMTP


@enduml